version: '3.9'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ehr
    depends_on:
      - mongo
  mongo-express: 
    container_name: mongo-express
    image: mongo-express
    ports: 
      - '8083:8081'
  socket:
    container_name: socket
    build:
      context: ./socket
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/ehr
volumes:
  data:
